<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CQRS\" />
    <Folder Include="DTOs\CreateDtos\" />
    <Folder Include="DTOs\ReadDtos\" />
    <Folder Include="DTOs\UpdateDtos\" />
    <Folder Include="Interfaces\Repositories\OrganizationRepositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Em.Core.Domain\Em.Core.Domain.csproj" />
  </ItemGroup>

</Project>
